// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Package native contains hand-written native (non-Terraform) type definitions
// for the memorydb service (namespaced scope, v1beta1 group). These types are
// NOT generated by make generate and must not be modified by the code generation
// pipeline.
package native
