//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package native

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueuePolicyRAW) DeepCopyInto(out *QueuePolicyRAW) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueuePolicyRAW.
func (in *QueuePolicyRAW) DeepCopy() *QueuePolicyRAW {
	if in == nil {
		return nil
	}
	out := new(QueuePolicyRAW)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QueuePolicyRAW) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueuePolicyRAWInitParameters) DeepCopyInto(out *QueuePolicyRAWInitParameters) {
	*out = *in
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(string)
		**out = **in
	}
	if in.QueueURL != nil {
		in, out := &in.QueueURL, &out.QueueURL
		*out = new(string)
		**out = **in
	}
	if in.QueueURLRef != nil {
		in, out := &in.QueueURLRef, &out.QueueURLRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.QueueURLSelector != nil {
		in, out := &in.QueueURLSelector, &out.QueueURLSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueuePolicyRAWInitParameters.
func (in *QueuePolicyRAWInitParameters) DeepCopy() *QueuePolicyRAWInitParameters {
	if in == nil {
		return nil
	}
	out := new(QueuePolicyRAWInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueuePolicyRAWList) DeepCopyInto(out *QueuePolicyRAWList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]QueuePolicyRAW, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueuePolicyRAWList.
func (in *QueuePolicyRAWList) DeepCopy() *QueuePolicyRAWList {
	if in == nil {
		return nil
	}
	out := new(QueuePolicyRAWList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QueuePolicyRAWList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueuePolicyRAWObservation) DeepCopyInto(out *QueuePolicyRAWObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.QueueURL != nil {
		in, out := &in.QueueURL, &out.QueueURL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueuePolicyRAWObservation.
func (in *QueuePolicyRAWObservation) DeepCopy() *QueuePolicyRAWObservation {
	if in == nil {
		return nil
	}
	out := new(QueuePolicyRAWObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueuePolicyRAWParameters) DeepCopyInto(out *QueuePolicyRAWParameters) {
	*out = *in
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(string)
		**out = **in
	}
	if in.QueueURL != nil {
		in, out := &in.QueueURL, &out.QueueURL
		*out = new(string)
		**out = **in
	}
	if in.QueueURLRef != nil {
		in, out := &in.QueueURLRef, &out.QueueURLRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.QueueURLSelector != nil {
		in, out := &in.QueueURLSelector, &out.QueueURLSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueuePolicyRAWParameters.
func (in *QueuePolicyRAWParameters) DeepCopy() *QueuePolicyRAWParameters {
	if in == nil {
		return nil
	}
	out := new(QueuePolicyRAWParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueuePolicyRAWSpec) DeepCopyInto(out *QueuePolicyRAWSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueuePolicyRAWSpec.
func (in *QueuePolicyRAWSpec) DeepCopy() *QueuePolicyRAWSpec {
	if in == nil {
		return nil
	}
	out := new(QueuePolicyRAWSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueuePolicyRAWStatus) DeepCopyInto(out *QueuePolicyRAWStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueuePolicyRAWStatus.
func (in *QueuePolicyRAWStatus) DeepCopy() *QueuePolicyRAWStatus {
	if in == nil {
		return nil
	}
	out := new(QueuePolicyRAWStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueRAW) DeepCopyInto(out *QueueRAW) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueRAW.
func (in *QueueRAW) DeepCopy() *QueueRAW {
	if in == nil {
		return nil
	}
	out := new(QueueRAW)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QueueRAW) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueRAWInitParameters) DeepCopyInto(out *QueueRAWInitParameters) {
	*out = *in
	if in.ContentBasedDeduplication != nil {
		in, out := &in.ContentBasedDeduplication, &out.ContentBasedDeduplication
		*out = new(bool)
		**out = **in
	}
	if in.DeduplicationScope != nil {
		in, out := &in.DeduplicationScope, &out.DeduplicationScope
		*out = new(string)
		**out = **in
	}
	if in.DelaySeconds != nil {
		in, out := &in.DelaySeconds, &out.DelaySeconds
		*out = new(float64)
		**out = **in
	}
	if in.FifoQueue != nil {
		in, out := &in.FifoQueue, &out.FifoQueue
		*out = new(bool)
		**out = **in
	}
	if in.FifoThroughputLimit != nil {
		in, out := &in.FifoThroughputLimit, &out.FifoThroughputLimit
		*out = new(string)
		**out = **in
	}
	if in.KMSDataKeyReusePeriodSeconds != nil {
		in, out := &in.KMSDataKeyReusePeriodSeconds, &out.KMSDataKeyReusePeriodSeconds
		*out = new(float64)
		**out = **in
	}
	if in.KMSMasterKeyID != nil {
		in, out := &in.KMSMasterKeyID, &out.KMSMasterKeyID
		*out = new(string)
		**out = **in
	}
	if in.MaxMessageSize != nil {
		in, out := &in.MaxMessageSize, &out.MaxMessageSize
		*out = new(float64)
		**out = **in
	}
	if in.MessageRetentionSeconds != nil {
		in, out := &in.MessageRetentionSeconds, &out.MessageRetentionSeconds
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(string)
		**out = **in
	}
	if in.ReceiveWaitTimeSeconds != nil {
		in, out := &in.ReceiveWaitTimeSeconds, &out.ReceiveWaitTimeSeconds
		*out = new(float64)
		**out = **in
	}
	if in.RedriveAllowPolicy != nil {
		in, out := &in.RedriveAllowPolicy, &out.RedriveAllowPolicy
		*out = new(string)
		**out = **in
	}
	if in.RedrivePolicy != nil {
		in, out := &in.RedrivePolicy, &out.RedrivePolicy
		*out = new(string)
		**out = **in
	}
	if in.SqsManagedSseEnabled != nil {
		in, out := &in.SqsManagedSseEnabled, &out.SqsManagedSseEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.VisibilityTimeoutSeconds != nil {
		in, out := &in.VisibilityTimeoutSeconds, &out.VisibilityTimeoutSeconds
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueRAWInitParameters.
func (in *QueueRAWInitParameters) DeepCopy() *QueueRAWInitParameters {
	if in == nil {
		return nil
	}
	out := new(QueueRAWInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueRAWList) DeepCopyInto(out *QueueRAWList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]QueueRAW, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueRAWList.
func (in *QueueRAWList) DeepCopy() *QueueRAWList {
	if in == nil {
		return nil
	}
	out := new(QueueRAWList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QueueRAWList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueRAWObservation) DeepCopyInto(out *QueueRAWObservation) {
	*out = *in
	if in.Arn != nil {
		in, out := &in.Arn, &out.Arn
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
	if in.TagsAll != nil {
		in, out := &in.TagsAll, &out.TagsAll
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueRAWObservation.
func (in *QueueRAWObservation) DeepCopy() *QueueRAWObservation {
	if in == nil {
		return nil
	}
	out := new(QueueRAWObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueRAWParameters) DeepCopyInto(out *QueueRAWParameters) {
	*out = *in
	if in.ContentBasedDeduplication != nil {
		in, out := &in.ContentBasedDeduplication, &out.ContentBasedDeduplication
		*out = new(bool)
		**out = **in
	}
	if in.DeduplicationScope != nil {
		in, out := &in.DeduplicationScope, &out.DeduplicationScope
		*out = new(string)
		**out = **in
	}
	if in.DelaySeconds != nil {
		in, out := &in.DelaySeconds, &out.DelaySeconds
		*out = new(float64)
		**out = **in
	}
	if in.FifoQueue != nil {
		in, out := &in.FifoQueue, &out.FifoQueue
		*out = new(bool)
		**out = **in
	}
	if in.FifoThroughputLimit != nil {
		in, out := &in.FifoThroughputLimit, &out.FifoThroughputLimit
		*out = new(string)
		**out = **in
	}
	if in.KMSDataKeyReusePeriodSeconds != nil {
		in, out := &in.KMSDataKeyReusePeriodSeconds, &out.KMSDataKeyReusePeriodSeconds
		*out = new(float64)
		**out = **in
	}
	if in.KMSMasterKeyID != nil {
		in, out := &in.KMSMasterKeyID, &out.KMSMasterKeyID
		*out = new(string)
		**out = **in
	}
	if in.MaxMessageSize != nil {
		in, out := &in.MaxMessageSize, &out.MaxMessageSize
		*out = new(float64)
		**out = **in
	}
	if in.MessageRetentionSeconds != nil {
		in, out := &in.MessageRetentionSeconds, &out.MessageRetentionSeconds
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(string)
		**out = **in
	}
	if in.ReceiveWaitTimeSeconds != nil {
		in, out := &in.ReceiveWaitTimeSeconds, &out.ReceiveWaitTimeSeconds
		*out = new(float64)
		**out = **in
	}
	if in.RedriveAllowPolicy != nil {
		in, out := &in.RedriveAllowPolicy, &out.RedriveAllowPolicy
		*out = new(string)
		**out = **in
	}
	if in.RedrivePolicy != nil {
		in, out := &in.RedrivePolicy, &out.RedrivePolicy
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.SqsManagedSseEnabled != nil {
		in, out := &in.SqsManagedSseEnabled, &out.SqsManagedSseEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.VisibilityTimeoutSeconds != nil {
		in, out := &in.VisibilityTimeoutSeconds, &out.VisibilityTimeoutSeconds
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueRAWParameters.
func (in *QueueRAWParameters) DeepCopy() *QueueRAWParameters {
	if in == nil {
		return nil
	}
	out := new(QueueRAWParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueRAWSpec) DeepCopyInto(out *QueueRAWSpec) {
	*out = *in
	if in.DeletionPolicy != nil {
		in, out := &in.DeletionPolicy, &out.DeletionPolicy
		*out = new(v1.DeletionPolicy)
		**out = **in
	}
	if in.WriteConnectionSecretToReference != nil {
		in, out := &in.WriteConnectionSecretToReference, &out.WriteConnectionSecretToReference
		*out = new(v1.SecretReference)
		**out = **in
	}
	if in.ProviderConfigReference != nil {
		in, out := &in.ProviderConfigReference, &out.ProviderConfigReference
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ManagementPolicies != nil {
		in, out := &in.ManagementPolicies, &out.ManagementPolicies
		*out = make(v1.ManagementPolicies, len(*in))
		copy(*out, *in)
	}
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueRAWSpec.
func (in *QueueRAWSpec) DeepCopy() *QueueRAWSpec {
	if in == nil {
		return nil
	}
	out := new(QueueRAWSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueRAWStatus) DeepCopyInto(out *QueueRAWStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueRAWStatus.
func (in *QueueRAWStatus) DeepCopy() *QueueRAWStatus {
	if in == nil {
		return nil
	}
	out := new(QueueRAWStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueRedriveAllowPolicyRAW) DeepCopyInto(out *QueueRedriveAllowPolicyRAW) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueRedriveAllowPolicyRAW.
func (in *QueueRedriveAllowPolicyRAW) DeepCopy() *QueueRedriveAllowPolicyRAW {
	if in == nil {
		return nil
	}
	out := new(QueueRedriveAllowPolicyRAW)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QueueRedriveAllowPolicyRAW) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueRedriveAllowPolicyRAWInitParameters) DeepCopyInto(out *QueueRedriveAllowPolicyRAWInitParameters) {
	*out = *in
	if in.QueueURL != nil {
		in, out := &in.QueueURL, &out.QueueURL
		*out = new(string)
		**out = **in
	}
	if in.QueueURLRef != nil {
		in, out := &in.QueueURLRef, &out.QueueURLRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.QueueURLSelector != nil {
		in, out := &in.QueueURLSelector, &out.QueueURLSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.RedriveAllowPolicy != nil {
		in, out := &in.RedriveAllowPolicy, &out.RedriveAllowPolicy
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueRedriveAllowPolicyRAWInitParameters.
func (in *QueueRedriveAllowPolicyRAWInitParameters) DeepCopy() *QueueRedriveAllowPolicyRAWInitParameters {
	if in == nil {
		return nil
	}
	out := new(QueueRedriveAllowPolicyRAWInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueRedriveAllowPolicyRAWList) DeepCopyInto(out *QueueRedriveAllowPolicyRAWList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]QueueRedriveAllowPolicyRAW, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueRedriveAllowPolicyRAWList.
func (in *QueueRedriveAllowPolicyRAWList) DeepCopy() *QueueRedriveAllowPolicyRAWList {
	if in == nil {
		return nil
	}
	out := new(QueueRedriveAllowPolicyRAWList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QueueRedriveAllowPolicyRAWList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueRedriveAllowPolicyRAWObservation) DeepCopyInto(out *QueueRedriveAllowPolicyRAWObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.QueueURL != nil {
		in, out := &in.QueueURL, &out.QueueURL
		*out = new(string)
		**out = **in
	}
	if in.RedriveAllowPolicy != nil {
		in, out := &in.RedriveAllowPolicy, &out.RedriveAllowPolicy
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueRedriveAllowPolicyRAWObservation.
func (in *QueueRedriveAllowPolicyRAWObservation) DeepCopy() *QueueRedriveAllowPolicyRAWObservation {
	if in == nil {
		return nil
	}
	out := new(QueueRedriveAllowPolicyRAWObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueRedriveAllowPolicyRAWParameters) DeepCopyInto(out *QueueRedriveAllowPolicyRAWParameters) {
	*out = *in
	if in.QueueURL != nil {
		in, out := &in.QueueURL, &out.QueueURL
		*out = new(string)
		**out = **in
	}
	if in.QueueURLRef != nil {
		in, out := &in.QueueURLRef, &out.QueueURLRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.QueueURLSelector != nil {
		in, out := &in.QueueURLSelector, &out.QueueURLSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.RedriveAllowPolicy != nil {
		in, out := &in.RedriveAllowPolicy, &out.RedriveAllowPolicy
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueRedriveAllowPolicyRAWParameters.
func (in *QueueRedriveAllowPolicyRAWParameters) DeepCopy() *QueueRedriveAllowPolicyRAWParameters {
	if in == nil {
		return nil
	}
	out := new(QueueRedriveAllowPolicyRAWParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueRedriveAllowPolicyRAWSpec) DeepCopyInto(out *QueueRedriveAllowPolicyRAWSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueRedriveAllowPolicyRAWSpec.
func (in *QueueRedriveAllowPolicyRAWSpec) DeepCopy() *QueueRedriveAllowPolicyRAWSpec {
	if in == nil {
		return nil
	}
	out := new(QueueRedriveAllowPolicyRAWSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueRedriveAllowPolicyRAWStatus) DeepCopyInto(out *QueueRedriveAllowPolicyRAWStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueRedriveAllowPolicyRAWStatus.
func (in *QueueRedriveAllowPolicyRAWStatus) DeepCopy() *QueueRedriveAllowPolicyRAWStatus {
	if in == nil {
		return nil
	}
	out := new(QueueRedriveAllowPolicyRAWStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueRedrivePolicyRAW) DeepCopyInto(out *QueueRedrivePolicyRAW) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueRedrivePolicyRAW.
func (in *QueueRedrivePolicyRAW) DeepCopy() *QueueRedrivePolicyRAW {
	if in == nil {
		return nil
	}
	out := new(QueueRedrivePolicyRAW)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QueueRedrivePolicyRAW) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueRedrivePolicyRAWInitParameters) DeepCopyInto(out *QueueRedrivePolicyRAWInitParameters) {
	*out = *in
	if in.QueueURL != nil {
		in, out := &in.QueueURL, &out.QueueURL
		*out = new(string)
		**out = **in
	}
	if in.QueueURLRef != nil {
		in, out := &in.QueueURLRef, &out.QueueURLRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.QueueURLSelector != nil {
		in, out := &in.QueueURLSelector, &out.QueueURLSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.RedrivePolicy != nil {
		in, out := &in.RedrivePolicy, &out.RedrivePolicy
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueRedrivePolicyRAWInitParameters.
func (in *QueueRedrivePolicyRAWInitParameters) DeepCopy() *QueueRedrivePolicyRAWInitParameters {
	if in == nil {
		return nil
	}
	out := new(QueueRedrivePolicyRAWInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueRedrivePolicyRAWList) DeepCopyInto(out *QueueRedrivePolicyRAWList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]QueueRedrivePolicyRAW, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueRedrivePolicyRAWList.
func (in *QueueRedrivePolicyRAWList) DeepCopy() *QueueRedrivePolicyRAWList {
	if in == nil {
		return nil
	}
	out := new(QueueRedrivePolicyRAWList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QueueRedrivePolicyRAWList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueRedrivePolicyRAWObservation) DeepCopyInto(out *QueueRedrivePolicyRAWObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.QueueURL != nil {
		in, out := &in.QueueURL, &out.QueueURL
		*out = new(string)
		**out = **in
	}
	if in.RedrivePolicy != nil {
		in, out := &in.RedrivePolicy, &out.RedrivePolicy
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueRedrivePolicyRAWObservation.
func (in *QueueRedrivePolicyRAWObservation) DeepCopy() *QueueRedrivePolicyRAWObservation {
	if in == nil {
		return nil
	}
	out := new(QueueRedrivePolicyRAWObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueRedrivePolicyRAWParameters) DeepCopyInto(out *QueueRedrivePolicyRAWParameters) {
	*out = *in
	if in.QueueURL != nil {
		in, out := &in.QueueURL, &out.QueueURL
		*out = new(string)
		**out = **in
	}
	if in.QueueURLRef != nil {
		in, out := &in.QueueURLRef, &out.QueueURLRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.QueueURLSelector != nil {
		in, out := &in.QueueURLSelector, &out.QueueURLSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.RedrivePolicy != nil {
		in, out := &in.RedrivePolicy, &out.RedrivePolicy
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueRedrivePolicyRAWParameters.
func (in *QueueRedrivePolicyRAWParameters) DeepCopy() *QueueRedrivePolicyRAWParameters {
	if in == nil {
		return nil
	}
	out := new(QueueRedrivePolicyRAWParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueRedrivePolicyRAWSpec) DeepCopyInto(out *QueueRedrivePolicyRAWSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueRedrivePolicyRAWSpec.
func (in *QueueRedrivePolicyRAWSpec) DeepCopy() *QueueRedrivePolicyRAWSpec {
	if in == nil {
		return nil
	}
	out := new(QueueRedrivePolicyRAWSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueRedrivePolicyRAWStatus) DeepCopyInto(out *QueueRedrivePolicyRAWStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueRedrivePolicyRAWStatus.
func (in *QueueRedrivePolicyRAWStatus) DeepCopy() *QueueRedrivePolicyRAWStatus {
	if in == nil {
		return nil
	}
	out := new(QueueRedrivePolicyRAWStatus)
	in.DeepCopyInto(out)
	return out
}
