// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by angryjet. DO NOT EDIT.

package native

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	errors "github.com/pkg/errors"
	v1beta1 "github.com/upbound/provider-aws/v2/apis/cluster/lambda/v1beta1"
	native1 "github.com/upbound/provider-aws/v2/apis/cluster/secretsmanager/v1beta1/native"
	native "github.com/upbound/provider-aws/v2/internal/native"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this SecretRotationRAW.
func (mg *SecretRotationRAW) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.RotationLambdaArn),
		Extract:      native.ExtractAtProviderField("arn"),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.RotationLambdaArnRef,
		Selector:     mg.Spec.ForProvider.RotationLambdaArnSelector,
		To: reference.To{
			List:    &v1beta1.FunctionList{},
			Managed: &v1beta1.Function{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.RotationLambdaArn")
	}
	mg.Spec.ForProvider.RotationLambdaArn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.RotationLambdaArnRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SecretID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.SecretIDRef,
		Selector:     mg.Spec.ForProvider.SecretIDSelector,
		To: reference.To{
			List:    &native1.SecretRAWList{},
			Managed: &native1.SecretRAW{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.SecretID")
	}
	mg.Spec.ForProvider.SecretID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.SecretIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.RotationLambdaArn),
		Extract:      native.ExtractAtProviderField("arn"),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.RotationLambdaArnRef,
		Selector:     mg.Spec.InitProvider.RotationLambdaArnSelector,
		To: reference.To{
			List:    &v1beta1.FunctionList{},
			Managed: &v1beta1.Function{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.RotationLambdaArn")
	}
	mg.Spec.InitProvider.RotationLambdaArn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.RotationLambdaArnRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.SecretID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.SecretIDRef,
		Selector:     mg.Spec.InitProvider.SecretIDSelector,
		To: reference.To{
			List:    &native1.SecretRAWList{},
			Managed: &native1.SecretRAW{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.SecretID")
	}
	mg.Spec.InitProvider.SecretID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.SecretIDRef = rsp.ResolvedReference

	return nil
}
