//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package native

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RotationRulesRAWInitParameters) DeepCopyInto(out *RotationRulesRAWInitParameters) {
	*out = *in
	if in.AutomaticallyAfterDays != nil {
		in, out := &in.AutomaticallyAfterDays, &out.AutomaticallyAfterDays
		*out = new(float64)
		**out = **in
	}
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(string)
		**out = **in
	}
	if in.ScheduleExpression != nil {
		in, out := &in.ScheduleExpression, &out.ScheduleExpression
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RotationRulesRAWInitParameters.
func (in *RotationRulesRAWInitParameters) DeepCopy() *RotationRulesRAWInitParameters {
	if in == nil {
		return nil
	}
	out := new(RotationRulesRAWInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RotationRulesRAWObservation) DeepCopyInto(out *RotationRulesRAWObservation) {
	*out = *in
	if in.AutomaticallyAfterDays != nil {
		in, out := &in.AutomaticallyAfterDays, &out.AutomaticallyAfterDays
		*out = new(float64)
		**out = **in
	}
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(string)
		**out = **in
	}
	if in.ScheduleExpression != nil {
		in, out := &in.ScheduleExpression, &out.ScheduleExpression
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RotationRulesRAWObservation.
func (in *RotationRulesRAWObservation) DeepCopy() *RotationRulesRAWObservation {
	if in == nil {
		return nil
	}
	out := new(RotationRulesRAWObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RotationRulesRAWParameters) DeepCopyInto(out *RotationRulesRAWParameters) {
	*out = *in
	if in.AutomaticallyAfterDays != nil {
		in, out := &in.AutomaticallyAfterDays, &out.AutomaticallyAfterDays
		*out = new(float64)
		**out = **in
	}
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(string)
		**out = **in
	}
	if in.ScheduleExpression != nil {
		in, out := &in.ScheduleExpression, &out.ScheduleExpression
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RotationRulesRAWParameters.
func (in *RotationRulesRAWParameters) DeepCopy() *RotationRulesRAWParameters {
	if in == nil {
		return nil
	}
	out := new(RotationRulesRAWParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRotationRAW) DeepCopyInto(out *SecretRotationRAW) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRotationRAW.
func (in *SecretRotationRAW) DeepCopy() *SecretRotationRAW {
	if in == nil {
		return nil
	}
	out := new(SecretRotationRAW)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecretRotationRAW) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRotationRAWInitParameters) DeepCopyInto(out *SecretRotationRAWInitParameters) {
	*out = *in
	if in.RotateImmediately != nil {
		in, out := &in.RotateImmediately, &out.RotateImmediately
		*out = new(bool)
		**out = **in
	}
	if in.RotationLambdaArn != nil {
		in, out := &in.RotationLambdaArn, &out.RotationLambdaArn
		*out = new(string)
		**out = **in
	}
	if in.RotationLambdaArnRef != nil {
		in, out := &in.RotationLambdaArnRef, &out.RotationLambdaArnRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.RotationLambdaArnSelector != nil {
		in, out := &in.RotationLambdaArnSelector, &out.RotationLambdaArnSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.RotationRules != nil {
		in, out := &in.RotationRules, &out.RotationRules
		*out = new(RotationRulesRAWInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.SecretID != nil {
		in, out := &in.SecretID, &out.SecretID
		*out = new(string)
		**out = **in
	}
	if in.SecretIDRef != nil {
		in, out := &in.SecretIDRef, &out.SecretIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.SecretIDSelector != nil {
		in, out := &in.SecretIDSelector, &out.SecretIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRotationRAWInitParameters.
func (in *SecretRotationRAWInitParameters) DeepCopy() *SecretRotationRAWInitParameters {
	if in == nil {
		return nil
	}
	out := new(SecretRotationRAWInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRotationRAWList) DeepCopyInto(out *SecretRotationRAWList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecretRotationRAW, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRotationRAWList.
func (in *SecretRotationRAWList) DeepCopy() *SecretRotationRAWList {
	if in == nil {
		return nil
	}
	out := new(SecretRotationRAWList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecretRotationRAWList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRotationRAWObservation) DeepCopyInto(out *SecretRotationRAWObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.RotationEnabled != nil {
		in, out := &in.RotationEnabled, &out.RotationEnabled
		*out = new(bool)
		**out = **in
	}
	if in.RotationLambdaArn != nil {
		in, out := &in.RotationLambdaArn, &out.RotationLambdaArn
		*out = new(string)
		**out = **in
	}
	if in.RotationRules != nil {
		in, out := &in.RotationRules, &out.RotationRules
		*out = new(RotationRulesRAWObservation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRotationRAWObservation.
func (in *SecretRotationRAWObservation) DeepCopy() *SecretRotationRAWObservation {
	if in == nil {
		return nil
	}
	out := new(SecretRotationRAWObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRotationRAWParameters) DeepCopyInto(out *SecretRotationRAWParameters) {
	*out = *in
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.RotateImmediately != nil {
		in, out := &in.RotateImmediately, &out.RotateImmediately
		*out = new(bool)
		**out = **in
	}
	if in.RotationLambdaArn != nil {
		in, out := &in.RotationLambdaArn, &out.RotationLambdaArn
		*out = new(string)
		**out = **in
	}
	if in.RotationLambdaArnRef != nil {
		in, out := &in.RotationLambdaArnRef, &out.RotationLambdaArnRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.RotationLambdaArnSelector != nil {
		in, out := &in.RotationLambdaArnSelector, &out.RotationLambdaArnSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.RotationRules != nil {
		in, out := &in.RotationRules, &out.RotationRules
		*out = new(RotationRulesRAWParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.SecretID != nil {
		in, out := &in.SecretID, &out.SecretID
		*out = new(string)
		**out = **in
	}
	if in.SecretIDRef != nil {
		in, out := &in.SecretIDRef, &out.SecretIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.SecretIDSelector != nil {
		in, out := &in.SecretIDSelector, &out.SecretIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRotationRAWParameters.
func (in *SecretRotationRAWParameters) DeepCopy() *SecretRotationRAWParameters {
	if in == nil {
		return nil
	}
	out := new(SecretRotationRAWParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRotationRAWSpec) DeepCopyInto(out *SecretRotationRAWSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRotationRAWSpec.
func (in *SecretRotationRAWSpec) DeepCopy() *SecretRotationRAWSpec {
	if in == nil {
		return nil
	}
	out := new(SecretRotationRAWSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRotationRAWStatus) DeepCopyInto(out *SecretRotationRAWStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRotationRAWStatus.
func (in *SecretRotationRAWStatus) DeepCopy() *SecretRotationRAWStatus {
	if in == nil {
		return nil
	}
	out := new(SecretRotationRAWStatus)
	in.DeepCopyInto(out)
	return out
}
