// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Package native contains hand-written native (non-Terraform) type definitions
// for the kinesis service (namespaced scope, v1beta2). These types are NOT
// generated by make generate and must not be modified by the code generation
// pipeline.
//
// v1beta2 is a served-but-not-storage version alias for the v1beta1 StreamRAW
// type. It exists so that example manifests referencing
// kinesis.aws.m.upbound.io/v1beta2/StreamRAW are accepted by the API server.
// All CRs submitted as v1beta2 are stored as v1beta1 (the storage version),
// and the v1beta1 controller reconciles them.

// +kubebuilder:object:generate=true
// +groupName=kinesis.aws.m.upbound.io
// +versionName=v1beta2
package native
