// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by angryjet. DO NOT EDIT.

package native

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	errors "github.com/pkg/errors"
	native "github.com/upbound/provider-aws/v2/internal/native"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this QueuePolicyRAW.
func (mg *QueuePolicyRAW) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.QueueURL),
		Extract:      native.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.QueueURLRef,
		Selector:     mg.Spec.ForProvider.QueueURLSelector,
		To: reference.To{
			List:    &QueueRAWList{},
			Managed: &QueueRAW{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.QueueURL")
	}
	mg.Spec.ForProvider.QueueURL = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.QueueURLRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.QueueURL),
		Extract:      native.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.QueueURLRef,
		Selector:     mg.Spec.InitProvider.QueueURLSelector,
		To: reference.To{
			List:    &QueueRAWList{},
			Managed: &QueueRAW{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.QueueURL")
	}
	mg.Spec.InitProvider.QueueURL = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.QueueURLRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this QueueRedriveAllowPolicyRAW.
func (mg *QueueRedriveAllowPolicyRAW) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.QueueURL),
		Extract:      native.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.QueueURLRef,
		Selector:     mg.Spec.ForProvider.QueueURLSelector,
		To: reference.To{
			List:    &QueueRAWList{},
			Managed: &QueueRAW{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.QueueURL")
	}
	mg.Spec.ForProvider.QueueURL = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.QueueURLRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.QueueURL),
		Extract:      native.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.QueueURLRef,
		Selector:     mg.Spec.InitProvider.QueueURLSelector,
		To: reference.To{
			List:    &QueueRAWList{},
			Managed: &QueueRAW{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.QueueURL")
	}
	mg.Spec.InitProvider.QueueURL = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.QueueURLRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this QueueRedrivePolicyRAW.
func (mg *QueueRedrivePolicyRAW) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.QueueURL),
		Extract:      native.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.QueueURLRef,
		Selector:     mg.Spec.ForProvider.QueueURLSelector,
		To: reference.To{
			List:    &QueueRAWList{},
			Managed: &QueueRAW{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.QueueURL")
	}
	mg.Spec.ForProvider.QueueURL = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.QueueURLRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.QueueURL),
		Extract:      native.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.QueueURLRef,
		Selector:     mg.Spec.InitProvider.QueueURLSelector,
		To: reference.To{
			List:    &QueueRAWList{},
			Managed: &QueueRAW{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.QueueURL")
	}
	mg.Spec.InitProvider.QueueURL = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.QueueURLRef = rsp.ResolvedReference

	return nil
}
