// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Package native contains hand-written native (non-Terraform) type definitions
// for the sfn service (namespaced scope). These types are NOT generated by
// make generate and must not be modified by the code generation pipeline.
//
// The namespaced RAW types reuse the Parameters, InitParameters, and
// Observation types from the cluster native package, differing only in the
// embedded Spec base type (xpv2.ManagedResourceSpec vs xpv1.ResourceSpec)
// and the resource scope annotation.
package native
