//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package native

import (
	runtime "k8s.io/apimachinery/pkg/runtime"

	clusternative "github.com/upbound/provider-aws/v2/apis/cluster/sfn/v1beta2/native"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StateMachineRAW) DeepCopyInto(out *StateMachineRAW) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StateMachineRAW.
func (in *StateMachineRAW) DeepCopy() *StateMachineRAW {
	if in == nil {
		return nil
	}
	out := new(StateMachineRAW)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StateMachineRAW) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StateMachineRAWList) DeepCopyInto(out *StateMachineRAWList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StateMachineRAW, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StateMachineRAWList.
func (in *StateMachineRAWList) DeepCopy() *StateMachineRAWList {
	if in == nil {
		return nil
	}
	out := new(StateMachineRAWList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StateMachineRAWList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StateMachineRAWSpec) DeepCopyInto(out *StateMachineRAWSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StateMachineRAWSpec.
func (in *StateMachineRAWSpec) DeepCopy() *StateMachineRAWSpec {
	if in == nil {
		return nil
	}
	out := new(StateMachineRAWSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StateMachineRAWStatus) DeepCopyInto(out *StateMachineRAWStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StateMachineRAWStatus.
func (in *StateMachineRAWStatus) DeepCopy() *StateMachineRAWStatus {
	if in == nil {
		return nil
	}
	out := new(StateMachineRAWStatus)
	in.DeepCopyInto(out)
	return out
}

// Ensure clusternative is used (referenced via Spec fields).
var _ = clusternative.StateMachineRAW_Kind
