// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by angryjet. DO NOT EDIT.

package native

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	errors "github.com/pkg/errors"
	v1beta1 "github.com/upbound/provider-aws/v2/apis/cluster/iam/v1beta1"
	v1beta11 "github.com/upbound/provider-aws/v2/apis/cluster/sqs/v1beta1"
	common "github.com/upbound/provider-aws/v2/config/cluster/common"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this TopicRAW.
func (mg *TopicRAW) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ApplicationFailureFeedbackRoleArn),
		Extract:      common.ARNExtractor(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ApplicationFailureFeedbackRoleArnRef,
		Selector:     mg.Spec.ForProvider.ApplicationFailureFeedbackRoleArnSelector,
		To: reference.To{
			List:    &v1beta1.RoleList{},
			Managed: &v1beta1.Role{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ApplicationFailureFeedbackRoleArn")
	}
	mg.Spec.ForProvider.ApplicationFailureFeedbackRoleArn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ApplicationFailureFeedbackRoleArnRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ApplicationSuccessFeedbackRoleArn),
		Extract:      common.ARNExtractor(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ApplicationSuccessFeedbackRoleArnRef,
		Selector:     mg.Spec.ForProvider.ApplicationSuccessFeedbackRoleArnSelector,
		To: reference.To{
			List:    &v1beta1.RoleList{},
			Managed: &v1beta1.Role{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ApplicationSuccessFeedbackRoleArn")
	}
	mg.Spec.ForProvider.ApplicationSuccessFeedbackRoleArn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ApplicationSuccessFeedbackRoleArnRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.FirehoseFailureFeedbackRoleArn),
		Extract:      common.ARNExtractor(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.FirehoseFailureFeedbackRoleArnRef,
		Selector:     mg.Spec.ForProvider.FirehoseFailureFeedbackRoleArnSelector,
		To: reference.To{
			List:    &v1beta1.RoleList{},
			Managed: &v1beta1.Role{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.FirehoseFailureFeedbackRoleArn")
	}
	mg.Spec.ForProvider.FirehoseFailureFeedbackRoleArn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.FirehoseFailureFeedbackRoleArnRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.FirehoseSuccessFeedbackRoleArn),
		Extract:      common.ARNExtractor(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.FirehoseSuccessFeedbackRoleArnRef,
		Selector:     mg.Spec.ForProvider.FirehoseSuccessFeedbackRoleArnSelector,
		To: reference.To{
			List:    &v1beta1.RoleList{},
			Managed: &v1beta1.Role{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.FirehoseSuccessFeedbackRoleArn")
	}
	mg.Spec.ForProvider.FirehoseSuccessFeedbackRoleArn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.FirehoseSuccessFeedbackRoleArnRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.HTTPFailureFeedbackRoleArn),
		Extract:      common.ARNExtractor(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.HTTPFailureFeedbackRoleArnRef,
		Selector:     mg.Spec.ForProvider.HTTPFailureFeedbackRoleArnSelector,
		To: reference.To{
			List:    &v1beta1.RoleList{},
			Managed: &v1beta1.Role{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.HTTPFailureFeedbackRoleArn")
	}
	mg.Spec.ForProvider.HTTPFailureFeedbackRoleArn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.HTTPFailureFeedbackRoleArnRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.HTTPSuccessFeedbackRoleArn),
		Extract:      common.ARNExtractor(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.HTTPSuccessFeedbackRoleArnRef,
		Selector:     mg.Spec.ForProvider.HTTPSuccessFeedbackRoleArnSelector,
		To: reference.To{
			List:    &v1beta1.RoleList{},
			Managed: &v1beta1.Role{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.HTTPSuccessFeedbackRoleArn")
	}
	mg.Spec.ForProvider.HTTPSuccessFeedbackRoleArn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.HTTPSuccessFeedbackRoleArnRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.LambdaFailureFeedbackRoleArn),
		Extract:      common.ARNExtractor(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.LambdaFailureFeedbackRoleArnRef,
		Selector:     mg.Spec.ForProvider.LambdaFailureFeedbackRoleArnSelector,
		To: reference.To{
			List:    &v1beta1.RoleList{},
			Managed: &v1beta1.Role{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.LambdaFailureFeedbackRoleArn")
	}
	mg.Spec.ForProvider.LambdaFailureFeedbackRoleArn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.LambdaFailureFeedbackRoleArnRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.LambdaSuccessFeedbackRoleArn),
		Extract:      common.ARNExtractor(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.LambdaSuccessFeedbackRoleArnRef,
		Selector:     mg.Spec.ForProvider.LambdaSuccessFeedbackRoleArnSelector,
		To: reference.To{
			List:    &v1beta1.RoleList{},
			Managed: &v1beta1.Role{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.LambdaSuccessFeedbackRoleArn")
	}
	mg.Spec.ForProvider.LambdaSuccessFeedbackRoleArn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.LambdaSuccessFeedbackRoleArnRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SqsFailureFeedbackRoleArn),
		Extract:      common.ARNExtractor(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.SqsFailureFeedbackRoleArnRef,
		Selector:     mg.Spec.ForProvider.SqsFailureFeedbackRoleArnSelector,
		To: reference.To{
			List:    &v1beta1.RoleList{},
			Managed: &v1beta1.Role{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.SqsFailureFeedbackRoleArn")
	}
	mg.Spec.ForProvider.SqsFailureFeedbackRoleArn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.SqsFailureFeedbackRoleArnRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SqsSuccessFeedbackRoleArn),
		Extract:      common.ARNExtractor(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.SqsSuccessFeedbackRoleArnRef,
		Selector:     mg.Spec.ForProvider.SqsSuccessFeedbackRoleArnSelector,
		To: reference.To{
			List:    &v1beta1.RoleList{},
			Managed: &v1beta1.Role{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.SqsSuccessFeedbackRoleArn")
	}
	mg.Spec.ForProvider.SqsSuccessFeedbackRoleArn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.SqsSuccessFeedbackRoleArnRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ApplicationFailureFeedbackRoleArn),
		Extract:      common.ARNExtractor(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ApplicationFailureFeedbackRoleArnRef,
		Selector:     mg.Spec.InitProvider.ApplicationFailureFeedbackRoleArnSelector,
		To: reference.To{
			List:    &v1beta1.RoleList{},
			Managed: &v1beta1.Role{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ApplicationFailureFeedbackRoleArn")
	}
	mg.Spec.InitProvider.ApplicationFailureFeedbackRoleArn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ApplicationFailureFeedbackRoleArnRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ApplicationSuccessFeedbackRoleArn),
		Extract:      common.ARNExtractor(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ApplicationSuccessFeedbackRoleArnRef,
		Selector:     mg.Spec.InitProvider.ApplicationSuccessFeedbackRoleArnSelector,
		To: reference.To{
			List:    &v1beta1.RoleList{},
			Managed: &v1beta1.Role{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ApplicationSuccessFeedbackRoleArn")
	}
	mg.Spec.InitProvider.ApplicationSuccessFeedbackRoleArn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ApplicationSuccessFeedbackRoleArnRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.FirehoseFailureFeedbackRoleArn),
		Extract:      common.ARNExtractor(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.FirehoseFailureFeedbackRoleArnRef,
		Selector:     mg.Spec.InitProvider.FirehoseFailureFeedbackRoleArnSelector,
		To: reference.To{
			List:    &v1beta1.RoleList{},
			Managed: &v1beta1.Role{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.FirehoseFailureFeedbackRoleArn")
	}
	mg.Spec.InitProvider.FirehoseFailureFeedbackRoleArn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.FirehoseFailureFeedbackRoleArnRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.FirehoseSuccessFeedbackRoleArn),
		Extract:      common.ARNExtractor(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.FirehoseSuccessFeedbackRoleArnRef,
		Selector:     mg.Spec.InitProvider.FirehoseSuccessFeedbackRoleArnSelector,
		To: reference.To{
			List:    &v1beta1.RoleList{},
			Managed: &v1beta1.Role{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.FirehoseSuccessFeedbackRoleArn")
	}
	mg.Spec.InitProvider.FirehoseSuccessFeedbackRoleArn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.FirehoseSuccessFeedbackRoleArnRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.HTTPFailureFeedbackRoleArn),
		Extract:      common.ARNExtractor(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.HTTPFailureFeedbackRoleArnRef,
		Selector:     mg.Spec.InitProvider.HTTPFailureFeedbackRoleArnSelector,
		To: reference.To{
			List:    &v1beta1.RoleList{},
			Managed: &v1beta1.Role{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.HTTPFailureFeedbackRoleArn")
	}
	mg.Spec.InitProvider.HTTPFailureFeedbackRoleArn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.HTTPFailureFeedbackRoleArnRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.HTTPSuccessFeedbackRoleArn),
		Extract:      common.ARNExtractor(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.HTTPSuccessFeedbackRoleArnRef,
		Selector:     mg.Spec.InitProvider.HTTPSuccessFeedbackRoleArnSelector,
		To: reference.To{
			List:    &v1beta1.RoleList{},
			Managed: &v1beta1.Role{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.HTTPSuccessFeedbackRoleArn")
	}
	mg.Spec.InitProvider.HTTPSuccessFeedbackRoleArn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.HTTPSuccessFeedbackRoleArnRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.LambdaFailureFeedbackRoleArn),
		Extract:      common.ARNExtractor(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.LambdaFailureFeedbackRoleArnRef,
		Selector:     mg.Spec.InitProvider.LambdaFailureFeedbackRoleArnSelector,
		To: reference.To{
			List:    &v1beta1.RoleList{},
			Managed: &v1beta1.Role{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.LambdaFailureFeedbackRoleArn")
	}
	mg.Spec.InitProvider.LambdaFailureFeedbackRoleArn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.LambdaFailureFeedbackRoleArnRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.LambdaSuccessFeedbackRoleArn),
		Extract:      common.ARNExtractor(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.LambdaSuccessFeedbackRoleArnRef,
		Selector:     mg.Spec.InitProvider.LambdaSuccessFeedbackRoleArnSelector,
		To: reference.To{
			List:    &v1beta1.RoleList{},
			Managed: &v1beta1.Role{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.LambdaSuccessFeedbackRoleArn")
	}
	mg.Spec.InitProvider.LambdaSuccessFeedbackRoleArn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.LambdaSuccessFeedbackRoleArnRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.SqsFailureFeedbackRoleArn),
		Extract:      common.ARNExtractor(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.SqsFailureFeedbackRoleArnRef,
		Selector:     mg.Spec.InitProvider.SqsFailureFeedbackRoleArnSelector,
		To: reference.To{
			List:    &v1beta1.RoleList{},
			Managed: &v1beta1.Role{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.SqsFailureFeedbackRoleArn")
	}
	mg.Spec.InitProvider.SqsFailureFeedbackRoleArn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.SqsFailureFeedbackRoleArnRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.SqsSuccessFeedbackRoleArn),
		Extract:      common.ARNExtractor(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.SqsSuccessFeedbackRoleArnRef,
		Selector:     mg.Spec.InitProvider.SqsSuccessFeedbackRoleArnSelector,
		To: reference.To{
			List:    &v1beta1.RoleList{},
			Managed: &v1beta1.Role{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.SqsSuccessFeedbackRoleArn")
	}
	mg.Spec.InitProvider.SqsSuccessFeedbackRoleArn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.SqsSuccessFeedbackRoleArnRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this TopicSubscriptionRAW.
func (mg *TopicSubscriptionRAW) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Endpoint),
		Extract:      common.ARNExtractor(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.EndpointRef,
		Selector:     mg.Spec.ForProvider.EndpointSelector,
		To: reference.To{
			List:    &v1beta11.QueueList{},
			Managed: &v1beta11.Queue{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Endpoint")
	}
	mg.Spec.ForProvider.Endpoint = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.EndpointRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SubscriptionRoleArn),
		Extract:      common.ARNExtractor(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.SubscriptionRoleArnRef,
		Selector:     mg.Spec.ForProvider.SubscriptionRoleArnSelector,
		To: reference.To{
			List:    &v1beta1.RoleList{},
			Managed: &v1beta1.Role{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.SubscriptionRoleArn")
	}
	mg.Spec.ForProvider.SubscriptionRoleArn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.SubscriptionRoleArnRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.TopicArn),
		Extract:      common.ARNExtractor(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.TopicArnRef,
		Selector:     mg.Spec.ForProvider.TopicArnSelector,
		To: reference.To{
			List:    &TopicRAWList{},
			Managed: &TopicRAW{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.TopicArn")
	}
	mg.Spec.ForProvider.TopicArn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.TopicArnRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Endpoint),
		Extract:      common.ARNExtractor(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.EndpointRef,
		Selector:     mg.Spec.InitProvider.EndpointSelector,
		To: reference.To{
			List:    &v1beta11.QueueList{},
			Managed: &v1beta11.Queue{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Endpoint")
	}
	mg.Spec.InitProvider.Endpoint = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.EndpointRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.SubscriptionRoleArn),
		Extract:      common.ARNExtractor(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.SubscriptionRoleArnRef,
		Selector:     mg.Spec.InitProvider.SubscriptionRoleArnSelector,
		To: reference.To{
			List:    &v1beta1.RoleList{},
			Managed: &v1beta1.Role{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.SubscriptionRoleArn")
	}
	mg.Spec.InitProvider.SubscriptionRoleArn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.SubscriptionRoleArnRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.TopicArn),
		Extract:      common.ARNExtractor(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.TopicArnRef,
		Selector:     mg.Spec.InitProvider.TopicArnSelector,
		To: reference.To{
			List:    &TopicRAWList{},
			Managed: &TopicRAW{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.TopicArn")
	}
	mg.Spec.InitProvider.TopicArn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.TopicArnRef = rsp.ResolvedReference

	return nil
}
