//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package native

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopicRAW) DeepCopyInto(out *TopicRAW) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopicRAW.
func (in *TopicRAW) DeepCopy() *TopicRAW {
	if in == nil {
		return nil
	}
	out := new(TopicRAW)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TopicRAW) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopicRAWInitParameters) DeepCopyInto(out *TopicRAWInitParameters) {
	*out = *in
	if in.ApplicationFailureFeedbackRoleArn != nil {
		in, out := &in.ApplicationFailureFeedbackRoleArn, &out.ApplicationFailureFeedbackRoleArn
		*out = new(string)
		**out = **in
	}
	if in.ApplicationFailureFeedbackRoleArnRef != nil {
		in, out := &in.ApplicationFailureFeedbackRoleArnRef, &out.ApplicationFailureFeedbackRoleArnRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.ApplicationFailureFeedbackRoleArnSelector != nil {
		in, out := &in.ApplicationFailureFeedbackRoleArnSelector, &out.ApplicationFailureFeedbackRoleArnSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ApplicationSuccessFeedbackRoleArn != nil {
		in, out := &in.ApplicationSuccessFeedbackRoleArn, &out.ApplicationSuccessFeedbackRoleArn
		*out = new(string)
		**out = **in
	}
	if in.ApplicationSuccessFeedbackRoleArnRef != nil {
		in, out := &in.ApplicationSuccessFeedbackRoleArnRef, &out.ApplicationSuccessFeedbackRoleArnRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.ApplicationSuccessFeedbackRoleArnSelector != nil {
		in, out := &in.ApplicationSuccessFeedbackRoleArnSelector, &out.ApplicationSuccessFeedbackRoleArnSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ApplicationSuccessFeedbackSampleRate != nil {
		in, out := &in.ApplicationSuccessFeedbackSampleRate, &out.ApplicationSuccessFeedbackSampleRate
		*out = new(float64)
		**out = **in
	}
	if in.ArchivePolicy != nil {
		in, out := &in.ArchivePolicy, &out.ArchivePolicy
		*out = new(string)
		**out = **in
	}
	if in.ContentBasedDeduplication != nil {
		in, out := &in.ContentBasedDeduplication, &out.ContentBasedDeduplication
		*out = new(bool)
		**out = **in
	}
	if in.DeliveryPolicy != nil {
		in, out := &in.DeliveryPolicy, &out.DeliveryPolicy
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.FifoThroughputScope != nil {
		in, out := &in.FifoThroughputScope, &out.FifoThroughputScope
		*out = new(string)
		**out = **in
	}
	if in.FifoTopic != nil {
		in, out := &in.FifoTopic, &out.FifoTopic
		*out = new(bool)
		**out = **in
	}
	if in.FirehoseFailureFeedbackRoleArn != nil {
		in, out := &in.FirehoseFailureFeedbackRoleArn, &out.FirehoseFailureFeedbackRoleArn
		*out = new(string)
		**out = **in
	}
	if in.FirehoseFailureFeedbackRoleArnRef != nil {
		in, out := &in.FirehoseFailureFeedbackRoleArnRef, &out.FirehoseFailureFeedbackRoleArnRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.FirehoseFailureFeedbackRoleArnSelector != nil {
		in, out := &in.FirehoseFailureFeedbackRoleArnSelector, &out.FirehoseFailureFeedbackRoleArnSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.FirehoseSuccessFeedbackRoleArn != nil {
		in, out := &in.FirehoseSuccessFeedbackRoleArn, &out.FirehoseSuccessFeedbackRoleArn
		*out = new(string)
		**out = **in
	}
	if in.FirehoseSuccessFeedbackRoleArnRef != nil {
		in, out := &in.FirehoseSuccessFeedbackRoleArnRef, &out.FirehoseSuccessFeedbackRoleArnRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.FirehoseSuccessFeedbackRoleArnSelector != nil {
		in, out := &in.FirehoseSuccessFeedbackRoleArnSelector, &out.FirehoseSuccessFeedbackRoleArnSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.FirehoseSuccessFeedbackSampleRate != nil {
		in, out := &in.FirehoseSuccessFeedbackSampleRate, &out.FirehoseSuccessFeedbackSampleRate
		*out = new(float64)
		**out = **in
	}
	if in.HTTPFailureFeedbackRoleArn != nil {
		in, out := &in.HTTPFailureFeedbackRoleArn, &out.HTTPFailureFeedbackRoleArn
		*out = new(string)
		**out = **in
	}
	if in.HTTPFailureFeedbackRoleArnRef != nil {
		in, out := &in.HTTPFailureFeedbackRoleArnRef, &out.HTTPFailureFeedbackRoleArnRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.HTTPFailureFeedbackRoleArnSelector != nil {
		in, out := &in.HTTPFailureFeedbackRoleArnSelector, &out.HTTPFailureFeedbackRoleArnSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.HTTPSuccessFeedbackRoleArn != nil {
		in, out := &in.HTTPSuccessFeedbackRoleArn, &out.HTTPSuccessFeedbackRoleArn
		*out = new(string)
		**out = **in
	}
	if in.HTTPSuccessFeedbackRoleArnRef != nil {
		in, out := &in.HTTPSuccessFeedbackRoleArnRef, &out.HTTPSuccessFeedbackRoleArnRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.HTTPSuccessFeedbackRoleArnSelector != nil {
		in, out := &in.HTTPSuccessFeedbackRoleArnSelector, &out.HTTPSuccessFeedbackRoleArnSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.HTTPSuccessFeedbackSampleRate != nil {
		in, out := &in.HTTPSuccessFeedbackSampleRate, &out.HTTPSuccessFeedbackSampleRate
		*out = new(float64)
		**out = **in
	}
	if in.KMSMasterKeyID != nil {
		in, out := &in.KMSMasterKeyID, &out.KMSMasterKeyID
		*out = new(string)
		**out = **in
	}
	if in.LambdaFailureFeedbackRoleArn != nil {
		in, out := &in.LambdaFailureFeedbackRoleArn, &out.LambdaFailureFeedbackRoleArn
		*out = new(string)
		**out = **in
	}
	if in.LambdaFailureFeedbackRoleArnRef != nil {
		in, out := &in.LambdaFailureFeedbackRoleArnRef, &out.LambdaFailureFeedbackRoleArnRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.LambdaFailureFeedbackRoleArnSelector != nil {
		in, out := &in.LambdaFailureFeedbackRoleArnSelector, &out.LambdaFailureFeedbackRoleArnSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.LambdaSuccessFeedbackRoleArn != nil {
		in, out := &in.LambdaSuccessFeedbackRoleArn, &out.LambdaSuccessFeedbackRoleArn
		*out = new(string)
		**out = **in
	}
	if in.LambdaSuccessFeedbackRoleArnRef != nil {
		in, out := &in.LambdaSuccessFeedbackRoleArnRef, &out.LambdaSuccessFeedbackRoleArnRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.LambdaSuccessFeedbackRoleArnSelector != nil {
		in, out := &in.LambdaSuccessFeedbackRoleArnSelector, &out.LambdaSuccessFeedbackRoleArnSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.LambdaSuccessFeedbackSampleRate != nil {
		in, out := &in.LambdaSuccessFeedbackSampleRate, &out.LambdaSuccessFeedbackSampleRate
		*out = new(float64)
		**out = **in
	}
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(string)
		**out = **in
	}
	if in.SignatureVersion != nil {
		in, out := &in.SignatureVersion, &out.SignatureVersion
		*out = new(float64)
		**out = **in
	}
	if in.SqsFailureFeedbackRoleArn != nil {
		in, out := &in.SqsFailureFeedbackRoleArn, &out.SqsFailureFeedbackRoleArn
		*out = new(string)
		**out = **in
	}
	if in.SqsFailureFeedbackRoleArnRef != nil {
		in, out := &in.SqsFailureFeedbackRoleArnRef, &out.SqsFailureFeedbackRoleArnRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.SqsFailureFeedbackRoleArnSelector != nil {
		in, out := &in.SqsFailureFeedbackRoleArnSelector, &out.SqsFailureFeedbackRoleArnSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.SqsSuccessFeedbackRoleArn != nil {
		in, out := &in.SqsSuccessFeedbackRoleArn, &out.SqsSuccessFeedbackRoleArn
		*out = new(string)
		**out = **in
	}
	if in.SqsSuccessFeedbackRoleArnRef != nil {
		in, out := &in.SqsSuccessFeedbackRoleArnRef, &out.SqsSuccessFeedbackRoleArnRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.SqsSuccessFeedbackRoleArnSelector != nil {
		in, out := &in.SqsSuccessFeedbackRoleArnSelector, &out.SqsSuccessFeedbackRoleArnSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.SqsSuccessFeedbackSampleRate != nil {
		in, out := &in.SqsSuccessFeedbackSampleRate, &out.SqsSuccessFeedbackSampleRate
		*out = new(float64)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.TracingConfig != nil {
		in, out := &in.TracingConfig, &out.TracingConfig
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopicRAWInitParameters.
func (in *TopicRAWInitParameters) DeepCopy() *TopicRAWInitParameters {
	if in == nil {
		return nil
	}
	out := new(TopicRAWInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopicRAWList) DeepCopyInto(out *TopicRAWList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TopicRAW, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopicRAWList.
func (in *TopicRAWList) DeepCopy() *TopicRAWList {
	if in == nil {
		return nil
	}
	out := new(TopicRAWList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TopicRAWList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopicRAWObservation) DeepCopyInto(out *TopicRAWObservation) {
	*out = *in
	if in.ApplicationFailureFeedbackRoleArn != nil {
		in, out := &in.ApplicationFailureFeedbackRoleArn, &out.ApplicationFailureFeedbackRoleArn
		*out = new(string)
		**out = **in
	}
	if in.ApplicationSuccessFeedbackRoleArn != nil {
		in, out := &in.ApplicationSuccessFeedbackRoleArn, &out.ApplicationSuccessFeedbackRoleArn
		*out = new(string)
		**out = **in
	}
	if in.ApplicationSuccessFeedbackSampleRate != nil {
		in, out := &in.ApplicationSuccessFeedbackSampleRate, &out.ApplicationSuccessFeedbackSampleRate
		*out = new(float64)
		**out = **in
	}
	if in.ArchivePolicy != nil {
		in, out := &in.ArchivePolicy, &out.ArchivePolicy
		*out = new(string)
		**out = **in
	}
	if in.Arn != nil {
		in, out := &in.Arn, &out.Arn
		*out = new(string)
		**out = **in
	}
	if in.BeginningArchiveTime != nil {
		in, out := &in.BeginningArchiveTime, &out.BeginningArchiveTime
		*out = new(string)
		**out = **in
	}
	if in.ContentBasedDeduplication != nil {
		in, out := &in.ContentBasedDeduplication, &out.ContentBasedDeduplication
		*out = new(bool)
		**out = **in
	}
	if in.DeliveryPolicy != nil {
		in, out := &in.DeliveryPolicy, &out.DeliveryPolicy
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.FifoThroughputScope != nil {
		in, out := &in.FifoThroughputScope, &out.FifoThroughputScope
		*out = new(string)
		**out = **in
	}
	if in.FifoTopic != nil {
		in, out := &in.FifoTopic, &out.FifoTopic
		*out = new(bool)
		**out = **in
	}
	if in.FirehoseFailureFeedbackRoleArn != nil {
		in, out := &in.FirehoseFailureFeedbackRoleArn, &out.FirehoseFailureFeedbackRoleArn
		*out = new(string)
		**out = **in
	}
	if in.FirehoseSuccessFeedbackRoleArn != nil {
		in, out := &in.FirehoseSuccessFeedbackRoleArn, &out.FirehoseSuccessFeedbackRoleArn
		*out = new(string)
		**out = **in
	}
	if in.FirehoseSuccessFeedbackSampleRate != nil {
		in, out := &in.FirehoseSuccessFeedbackSampleRate, &out.FirehoseSuccessFeedbackSampleRate
		*out = new(float64)
		**out = **in
	}
	if in.HTTPFailureFeedbackRoleArn != nil {
		in, out := &in.HTTPFailureFeedbackRoleArn, &out.HTTPFailureFeedbackRoleArn
		*out = new(string)
		**out = **in
	}
	if in.HTTPSuccessFeedbackRoleArn != nil {
		in, out := &in.HTTPSuccessFeedbackRoleArn, &out.HTTPSuccessFeedbackRoleArn
		*out = new(string)
		**out = **in
	}
	if in.HTTPSuccessFeedbackSampleRate != nil {
		in, out := &in.HTTPSuccessFeedbackSampleRate, &out.HTTPSuccessFeedbackSampleRate
		*out = new(float64)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.KMSMasterKeyID != nil {
		in, out := &in.KMSMasterKeyID, &out.KMSMasterKeyID
		*out = new(string)
		**out = **in
	}
	if in.LambdaFailureFeedbackRoleArn != nil {
		in, out := &in.LambdaFailureFeedbackRoleArn, &out.LambdaFailureFeedbackRoleArn
		*out = new(string)
		**out = **in
	}
	if in.LambdaSuccessFeedbackRoleArn != nil {
		in, out := &in.LambdaSuccessFeedbackRoleArn, &out.LambdaSuccessFeedbackRoleArn
		*out = new(string)
		**out = **in
	}
	if in.LambdaSuccessFeedbackSampleRate != nil {
		in, out := &in.LambdaSuccessFeedbackSampleRate, &out.LambdaSuccessFeedbackSampleRate
		*out = new(float64)
		**out = **in
	}
	if in.Owner != nil {
		in, out := &in.Owner, &out.Owner
		*out = new(string)
		**out = **in
	}
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.SignatureVersion != nil {
		in, out := &in.SignatureVersion, &out.SignatureVersion
		*out = new(float64)
		**out = **in
	}
	if in.SqsFailureFeedbackRoleArn != nil {
		in, out := &in.SqsFailureFeedbackRoleArn, &out.SqsFailureFeedbackRoleArn
		*out = new(string)
		**out = **in
	}
	if in.SqsSuccessFeedbackRoleArn != nil {
		in, out := &in.SqsSuccessFeedbackRoleArn, &out.SqsSuccessFeedbackRoleArn
		*out = new(string)
		**out = **in
	}
	if in.SqsSuccessFeedbackSampleRate != nil {
		in, out := &in.SqsSuccessFeedbackSampleRate, &out.SqsSuccessFeedbackSampleRate
		*out = new(float64)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.TagsAll != nil {
		in, out := &in.TagsAll, &out.TagsAll
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.TracingConfig != nil {
		in, out := &in.TracingConfig, &out.TracingConfig
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopicRAWObservation.
func (in *TopicRAWObservation) DeepCopy() *TopicRAWObservation {
	if in == nil {
		return nil
	}
	out := new(TopicRAWObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopicRAWParameters) DeepCopyInto(out *TopicRAWParameters) {
	*out = *in
	if in.ApplicationFailureFeedbackRoleArn != nil {
		in, out := &in.ApplicationFailureFeedbackRoleArn, &out.ApplicationFailureFeedbackRoleArn
		*out = new(string)
		**out = **in
	}
	if in.ApplicationFailureFeedbackRoleArnRef != nil {
		in, out := &in.ApplicationFailureFeedbackRoleArnRef, &out.ApplicationFailureFeedbackRoleArnRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.ApplicationFailureFeedbackRoleArnSelector != nil {
		in, out := &in.ApplicationFailureFeedbackRoleArnSelector, &out.ApplicationFailureFeedbackRoleArnSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ApplicationSuccessFeedbackRoleArn != nil {
		in, out := &in.ApplicationSuccessFeedbackRoleArn, &out.ApplicationSuccessFeedbackRoleArn
		*out = new(string)
		**out = **in
	}
	if in.ApplicationSuccessFeedbackRoleArnRef != nil {
		in, out := &in.ApplicationSuccessFeedbackRoleArnRef, &out.ApplicationSuccessFeedbackRoleArnRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.ApplicationSuccessFeedbackRoleArnSelector != nil {
		in, out := &in.ApplicationSuccessFeedbackRoleArnSelector, &out.ApplicationSuccessFeedbackRoleArnSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ApplicationSuccessFeedbackSampleRate != nil {
		in, out := &in.ApplicationSuccessFeedbackSampleRate, &out.ApplicationSuccessFeedbackSampleRate
		*out = new(float64)
		**out = **in
	}
	if in.ArchivePolicy != nil {
		in, out := &in.ArchivePolicy, &out.ArchivePolicy
		*out = new(string)
		**out = **in
	}
	if in.ContentBasedDeduplication != nil {
		in, out := &in.ContentBasedDeduplication, &out.ContentBasedDeduplication
		*out = new(bool)
		**out = **in
	}
	if in.DeliveryPolicy != nil {
		in, out := &in.DeliveryPolicy, &out.DeliveryPolicy
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.FifoThroughputScope != nil {
		in, out := &in.FifoThroughputScope, &out.FifoThroughputScope
		*out = new(string)
		**out = **in
	}
	if in.FifoTopic != nil {
		in, out := &in.FifoTopic, &out.FifoTopic
		*out = new(bool)
		**out = **in
	}
	if in.FirehoseFailureFeedbackRoleArn != nil {
		in, out := &in.FirehoseFailureFeedbackRoleArn, &out.FirehoseFailureFeedbackRoleArn
		*out = new(string)
		**out = **in
	}
	if in.FirehoseFailureFeedbackRoleArnRef != nil {
		in, out := &in.FirehoseFailureFeedbackRoleArnRef, &out.FirehoseFailureFeedbackRoleArnRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.FirehoseFailureFeedbackRoleArnSelector != nil {
		in, out := &in.FirehoseFailureFeedbackRoleArnSelector, &out.FirehoseFailureFeedbackRoleArnSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.FirehoseSuccessFeedbackRoleArn != nil {
		in, out := &in.FirehoseSuccessFeedbackRoleArn, &out.FirehoseSuccessFeedbackRoleArn
		*out = new(string)
		**out = **in
	}
	if in.FirehoseSuccessFeedbackRoleArnRef != nil {
		in, out := &in.FirehoseSuccessFeedbackRoleArnRef, &out.FirehoseSuccessFeedbackRoleArnRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.FirehoseSuccessFeedbackRoleArnSelector != nil {
		in, out := &in.FirehoseSuccessFeedbackRoleArnSelector, &out.FirehoseSuccessFeedbackRoleArnSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.FirehoseSuccessFeedbackSampleRate != nil {
		in, out := &in.FirehoseSuccessFeedbackSampleRate, &out.FirehoseSuccessFeedbackSampleRate
		*out = new(float64)
		**out = **in
	}
	if in.HTTPFailureFeedbackRoleArn != nil {
		in, out := &in.HTTPFailureFeedbackRoleArn, &out.HTTPFailureFeedbackRoleArn
		*out = new(string)
		**out = **in
	}
	if in.HTTPFailureFeedbackRoleArnRef != nil {
		in, out := &in.HTTPFailureFeedbackRoleArnRef, &out.HTTPFailureFeedbackRoleArnRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.HTTPFailureFeedbackRoleArnSelector != nil {
		in, out := &in.HTTPFailureFeedbackRoleArnSelector, &out.HTTPFailureFeedbackRoleArnSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.HTTPSuccessFeedbackRoleArn != nil {
		in, out := &in.HTTPSuccessFeedbackRoleArn, &out.HTTPSuccessFeedbackRoleArn
		*out = new(string)
		**out = **in
	}
	if in.HTTPSuccessFeedbackRoleArnRef != nil {
		in, out := &in.HTTPSuccessFeedbackRoleArnRef, &out.HTTPSuccessFeedbackRoleArnRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.HTTPSuccessFeedbackRoleArnSelector != nil {
		in, out := &in.HTTPSuccessFeedbackRoleArnSelector, &out.HTTPSuccessFeedbackRoleArnSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.HTTPSuccessFeedbackSampleRate != nil {
		in, out := &in.HTTPSuccessFeedbackSampleRate, &out.HTTPSuccessFeedbackSampleRate
		*out = new(float64)
		**out = **in
	}
	if in.KMSMasterKeyID != nil {
		in, out := &in.KMSMasterKeyID, &out.KMSMasterKeyID
		*out = new(string)
		**out = **in
	}
	if in.LambdaFailureFeedbackRoleArn != nil {
		in, out := &in.LambdaFailureFeedbackRoleArn, &out.LambdaFailureFeedbackRoleArn
		*out = new(string)
		**out = **in
	}
	if in.LambdaFailureFeedbackRoleArnRef != nil {
		in, out := &in.LambdaFailureFeedbackRoleArnRef, &out.LambdaFailureFeedbackRoleArnRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.LambdaFailureFeedbackRoleArnSelector != nil {
		in, out := &in.LambdaFailureFeedbackRoleArnSelector, &out.LambdaFailureFeedbackRoleArnSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.LambdaSuccessFeedbackRoleArn != nil {
		in, out := &in.LambdaSuccessFeedbackRoleArn, &out.LambdaSuccessFeedbackRoleArn
		*out = new(string)
		**out = **in
	}
	if in.LambdaSuccessFeedbackRoleArnRef != nil {
		in, out := &in.LambdaSuccessFeedbackRoleArnRef, &out.LambdaSuccessFeedbackRoleArnRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.LambdaSuccessFeedbackRoleArnSelector != nil {
		in, out := &in.LambdaSuccessFeedbackRoleArnSelector, &out.LambdaSuccessFeedbackRoleArnSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.LambdaSuccessFeedbackSampleRate != nil {
		in, out := &in.LambdaSuccessFeedbackSampleRate, &out.LambdaSuccessFeedbackSampleRate
		*out = new(float64)
		**out = **in
	}
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.SignatureVersion != nil {
		in, out := &in.SignatureVersion, &out.SignatureVersion
		*out = new(float64)
		**out = **in
	}
	if in.SqsFailureFeedbackRoleArn != nil {
		in, out := &in.SqsFailureFeedbackRoleArn, &out.SqsFailureFeedbackRoleArn
		*out = new(string)
		**out = **in
	}
	if in.SqsFailureFeedbackRoleArnRef != nil {
		in, out := &in.SqsFailureFeedbackRoleArnRef, &out.SqsFailureFeedbackRoleArnRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.SqsFailureFeedbackRoleArnSelector != nil {
		in, out := &in.SqsFailureFeedbackRoleArnSelector, &out.SqsFailureFeedbackRoleArnSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.SqsSuccessFeedbackRoleArn != nil {
		in, out := &in.SqsSuccessFeedbackRoleArn, &out.SqsSuccessFeedbackRoleArn
		*out = new(string)
		**out = **in
	}
	if in.SqsSuccessFeedbackRoleArnRef != nil {
		in, out := &in.SqsSuccessFeedbackRoleArnRef, &out.SqsSuccessFeedbackRoleArnRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.SqsSuccessFeedbackRoleArnSelector != nil {
		in, out := &in.SqsSuccessFeedbackRoleArnSelector, &out.SqsSuccessFeedbackRoleArnSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.SqsSuccessFeedbackSampleRate != nil {
		in, out := &in.SqsSuccessFeedbackSampleRate, &out.SqsSuccessFeedbackSampleRate
		*out = new(float64)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.TracingConfig != nil {
		in, out := &in.TracingConfig, &out.TracingConfig
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopicRAWParameters.
func (in *TopicRAWParameters) DeepCopy() *TopicRAWParameters {
	if in == nil {
		return nil
	}
	out := new(TopicRAWParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopicRAWSpec) DeepCopyInto(out *TopicRAWSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopicRAWSpec.
func (in *TopicRAWSpec) DeepCopy() *TopicRAWSpec {
	if in == nil {
		return nil
	}
	out := new(TopicRAWSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopicRAWStatus) DeepCopyInto(out *TopicRAWStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopicRAWStatus.
func (in *TopicRAWStatus) DeepCopy() *TopicRAWStatus {
	if in == nil {
		return nil
	}
	out := new(TopicRAWStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopicSubscriptionRAW) DeepCopyInto(out *TopicSubscriptionRAW) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopicSubscriptionRAW.
func (in *TopicSubscriptionRAW) DeepCopy() *TopicSubscriptionRAW {
	if in == nil {
		return nil
	}
	out := new(TopicSubscriptionRAW)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TopicSubscriptionRAW) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopicSubscriptionRAWInitParameters) DeepCopyInto(out *TopicSubscriptionRAWInitParameters) {
	*out = *in
	if in.ConfirmationTimeoutInMinutes != nil {
		in, out := &in.ConfirmationTimeoutInMinutes, &out.ConfirmationTimeoutInMinutes
		*out = new(float64)
		**out = **in
	}
	if in.DeliveryPolicy != nil {
		in, out := &in.DeliveryPolicy, &out.DeliveryPolicy
		*out = new(string)
		**out = **in
	}
	if in.Endpoint != nil {
		in, out := &in.Endpoint, &out.Endpoint
		*out = new(string)
		**out = **in
	}
	if in.EndpointRef != nil {
		in, out := &in.EndpointRef, &out.EndpointRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.EndpointSelector != nil {
		in, out := &in.EndpointSelector, &out.EndpointSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.EndpointAutoConfirms != nil {
		in, out := &in.EndpointAutoConfirms, &out.EndpointAutoConfirms
		*out = new(bool)
		**out = **in
	}
	if in.FilterPolicy != nil {
		in, out := &in.FilterPolicy, &out.FilterPolicy
		*out = new(string)
		**out = **in
	}
	if in.FilterPolicyScope != nil {
		in, out := &in.FilterPolicyScope, &out.FilterPolicyScope
		*out = new(string)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	if in.RawMessageDelivery != nil {
		in, out := &in.RawMessageDelivery, &out.RawMessageDelivery
		*out = new(bool)
		**out = **in
	}
	if in.RedrivePolicy != nil {
		in, out := &in.RedrivePolicy, &out.RedrivePolicy
		*out = new(string)
		**out = **in
	}
	if in.ReplayPolicy != nil {
		in, out := &in.ReplayPolicy, &out.ReplayPolicy
		*out = new(string)
		**out = **in
	}
	if in.SubscriptionRoleArn != nil {
		in, out := &in.SubscriptionRoleArn, &out.SubscriptionRoleArn
		*out = new(string)
		**out = **in
	}
	if in.SubscriptionRoleArnRef != nil {
		in, out := &in.SubscriptionRoleArnRef, &out.SubscriptionRoleArnRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.SubscriptionRoleArnSelector != nil {
		in, out := &in.SubscriptionRoleArnSelector, &out.SubscriptionRoleArnSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.TopicArn != nil {
		in, out := &in.TopicArn, &out.TopicArn
		*out = new(string)
		**out = **in
	}
	if in.TopicArnRef != nil {
		in, out := &in.TopicArnRef, &out.TopicArnRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.TopicArnSelector != nil {
		in, out := &in.TopicArnSelector, &out.TopicArnSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopicSubscriptionRAWInitParameters.
func (in *TopicSubscriptionRAWInitParameters) DeepCopy() *TopicSubscriptionRAWInitParameters {
	if in == nil {
		return nil
	}
	out := new(TopicSubscriptionRAWInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopicSubscriptionRAWList) DeepCopyInto(out *TopicSubscriptionRAWList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TopicSubscriptionRAW, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopicSubscriptionRAWList.
func (in *TopicSubscriptionRAWList) DeepCopy() *TopicSubscriptionRAWList {
	if in == nil {
		return nil
	}
	out := new(TopicSubscriptionRAWList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TopicSubscriptionRAWList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopicSubscriptionRAWObservation) DeepCopyInto(out *TopicSubscriptionRAWObservation) {
	*out = *in
	if in.Arn != nil {
		in, out := &in.Arn, &out.Arn
		*out = new(string)
		**out = **in
	}
	if in.ConfirmationTimeoutInMinutes != nil {
		in, out := &in.ConfirmationTimeoutInMinutes, &out.ConfirmationTimeoutInMinutes
		*out = new(float64)
		**out = **in
	}
	if in.ConfirmationWasAuthenticated != nil {
		in, out := &in.ConfirmationWasAuthenticated, &out.ConfirmationWasAuthenticated
		*out = new(bool)
		**out = **in
	}
	if in.DeliveryPolicy != nil {
		in, out := &in.DeliveryPolicy, &out.DeliveryPolicy
		*out = new(string)
		**out = **in
	}
	if in.Endpoint != nil {
		in, out := &in.Endpoint, &out.Endpoint
		*out = new(string)
		**out = **in
	}
	if in.EndpointAutoConfirms != nil {
		in, out := &in.EndpointAutoConfirms, &out.EndpointAutoConfirms
		*out = new(bool)
		**out = **in
	}
	if in.FilterPolicy != nil {
		in, out := &in.FilterPolicy, &out.FilterPolicy
		*out = new(string)
		**out = **in
	}
	if in.FilterPolicyScope != nil {
		in, out := &in.FilterPolicyScope, &out.FilterPolicyScope
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.OwnerID != nil {
		in, out := &in.OwnerID, &out.OwnerID
		*out = new(string)
		**out = **in
	}
	if in.PendingConfirmation != nil {
		in, out := &in.PendingConfirmation, &out.PendingConfirmation
		*out = new(bool)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	if in.RawMessageDelivery != nil {
		in, out := &in.RawMessageDelivery, &out.RawMessageDelivery
		*out = new(bool)
		**out = **in
	}
	if in.RedrivePolicy != nil {
		in, out := &in.RedrivePolicy, &out.RedrivePolicy
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.ReplayPolicy != nil {
		in, out := &in.ReplayPolicy, &out.ReplayPolicy
		*out = new(string)
		**out = **in
	}
	if in.SubscriptionRoleArn != nil {
		in, out := &in.SubscriptionRoleArn, &out.SubscriptionRoleArn
		*out = new(string)
		**out = **in
	}
	if in.TopicArn != nil {
		in, out := &in.TopicArn, &out.TopicArn
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopicSubscriptionRAWObservation.
func (in *TopicSubscriptionRAWObservation) DeepCopy() *TopicSubscriptionRAWObservation {
	if in == nil {
		return nil
	}
	out := new(TopicSubscriptionRAWObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopicSubscriptionRAWParameters) DeepCopyInto(out *TopicSubscriptionRAWParameters) {
	*out = *in
	if in.ConfirmationTimeoutInMinutes != nil {
		in, out := &in.ConfirmationTimeoutInMinutes, &out.ConfirmationTimeoutInMinutes
		*out = new(float64)
		**out = **in
	}
	if in.DeliveryPolicy != nil {
		in, out := &in.DeliveryPolicy, &out.DeliveryPolicy
		*out = new(string)
		**out = **in
	}
	if in.Endpoint != nil {
		in, out := &in.Endpoint, &out.Endpoint
		*out = new(string)
		**out = **in
	}
	if in.EndpointRef != nil {
		in, out := &in.EndpointRef, &out.EndpointRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.EndpointSelector != nil {
		in, out := &in.EndpointSelector, &out.EndpointSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.EndpointAutoConfirms != nil {
		in, out := &in.EndpointAutoConfirms, &out.EndpointAutoConfirms
		*out = new(bool)
		**out = **in
	}
	if in.FilterPolicy != nil {
		in, out := &in.FilterPolicy, &out.FilterPolicy
		*out = new(string)
		**out = **in
	}
	if in.FilterPolicyScope != nil {
		in, out := &in.FilterPolicyScope, &out.FilterPolicyScope
		*out = new(string)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	if in.RawMessageDelivery != nil {
		in, out := &in.RawMessageDelivery, &out.RawMessageDelivery
		*out = new(bool)
		**out = **in
	}
	if in.RedrivePolicy != nil {
		in, out := &in.RedrivePolicy, &out.RedrivePolicy
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.ReplayPolicy != nil {
		in, out := &in.ReplayPolicy, &out.ReplayPolicy
		*out = new(string)
		**out = **in
	}
	if in.SubscriptionRoleArn != nil {
		in, out := &in.SubscriptionRoleArn, &out.SubscriptionRoleArn
		*out = new(string)
		**out = **in
	}
	if in.SubscriptionRoleArnRef != nil {
		in, out := &in.SubscriptionRoleArnRef, &out.SubscriptionRoleArnRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.SubscriptionRoleArnSelector != nil {
		in, out := &in.SubscriptionRoleArnSelector, &out.SubscriptionRoleArnSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.TopicArn != nil {
		in, out := &in.TopicArn, &out.TopicArn
		*out = new(string)
		**out = **in
	}
	if in.TopicArnRef != nil {
		in, out := &in.TopicArnRef, &out.TopicArnRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.TopicArnSelector != nil {
		in, out := &in.TopicArnSelector, &out.TopicArnSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopicSubscriptionRAWParameters.
func (in *TopicSubscriptionRAWParameters) DeepCopy() *TopicSubscriptionRAWParameters {
	if in == nil {
		return nil
	}
	out := new(TopicSubscriptionRAWParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopicSubscriptionRAWSpec) DeepCopyInto(out *TopicSubscriptionRAWSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopicSubscriptionRAWSpec.
func (in *TopicSubscriptionRAWSpec) DeepCopy() *TopicSubscriptionRAWSpec {
	if in == nil {
		return nil
	}
	out := new(TopicSubscriptionRAWSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopicSubscriptionRAWStatus) DeepCopyInto(out *TopicSubscriptionRAWStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopicSubscriptionRAWStatus.
func (in *TopicSubscriptionRAWStatus) DeepCopy() *TopicSubscriptionRAWStatus {
	if in == nil {
		return nil
	}
	out := new(TopicSubscriptionRAWStatus)
	in.DeepCopyInto(out)
	return out
}
