# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: elasticache.aws.m.upbound.io/v1beta1
kind: GlobalReplicationGroupRAW
metadata:
  annotations:
    uptest.upbound.io/timeout: "3600"
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: default
spec:
  forProvider:
    globalReplicationGroupIdSuffix: example
    globalReplicationGroupDescription: example
    region: us-west-2
    primaryReplicationGroupIdRef:
      name: example
