# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: elasticache.aws.m.upbound.io/v1beta1
kind: ServerlessCacheRAW
metadata:
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: default
spec:
  forProvider:
    engine: redis
    region: us-east-1
