# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: elasticache.aws.m.upbound.io/v1beta2
kind: UserRAW
metadata:
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: default
spec:
  forProvider:
    accessString: "on ~app::* -@all +@read"
    engine: redis
    noPasswordRequired: true
    region: us-east-1
    userName: exampleuser
