// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Package native contains hand-written native (non-Terraform) type definitions
// for the kinesis service (namespaced scope). These types are NOT generated by
// make generate and must not be modified by the code generation pipeline.
//
// The namespaced RAW types define their own Parameters/InitParameters structs
// (not imported from cluster) for angryjet compatibility, with scope-appropriate
// reference annotations pointing to apis/namespaced/... types.
package native
