# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: sqs.aws.m.upbound.io/v1beta1
kind: QueueRedrivePolicyRAW
metadata:
  annotations:
    upjet.upbound.io/manual-intervention: "It requires a real queue arn to be specified."
    meta.upbound.io/example-id: sqs/v1beta1/queueredrivepolicyraw
  labels:
    testing.upbound.io/example-name: example
  name: qrpexample
  namespace: upbound-system
spec:
  forProvider:
    redrivePolicy: '{"deadLetterTargetArn":"arn:aws:sqs:us-east-1:609897127049:examplequeue-ddl-ns","maxReceiveCount":4}'
    region: us-east-1
    queueUrlSelector:
      matchLabels:
        testing.upbound.io/example-name: example
---
apiVersion: sqs.aws.m.upbound.io/v1beta1
kind: QueueRAW
metadata:
  annotations:
    meta.upbound.io/example-id: sqs/v1beta1/queueredrivepolicyraw
  labels:
    testing.upbound.io/example-name: ddl
  name: ddl
  namespace: upbound-system
spec:
  forProvider:
    name: examplequeue-ddl-ns
    redriveAllowPolicy: '{"redrivePermission":"byQueue","sourceQueueArns":["arn:aws:sqs:us-east-1:609897127049:examplequeue-ns"]}'
    region: us-east-1
---
apiVersion: sqs.aws.m.upbound.io/v1beta1
kind: QueueRAW
metadata:
  annotations:
    meta.upbound.io/example-id: sqs/v1beta1/queueredrivepolicyraw
  labels:
    testing.upbound.io/example-name: example
  name: qrpexample
  namespace: upbound-system
spec:
  forProvider:
    name: examplequeue-ns
    region: us-east-1
