// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by angryjet. DO NOT EDIT.
// NOTE: GlobalReplicationGroupRAW and SubnetGroupRAW are resolved via the
// apisresolver registry to avoid an import cycle:
//   v1beta1/native already imports v1beta2/native (for hub conversion),
//   so v1beta2/native cannot directly import v1beta1/native.

package native

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	errors "github.com/pkg/errors"
	v1beta11 "github.com/upbound/provider-aws/v2/apis/namespaced/ec2/v1beta1"
	v1beta1 "github.com/upbound/provider-aws/v2/apis/namespaced/kms/v1beta1"
	apisresolver "github.com/upbound/provider-aws/v2/internal/apis"
	native "github.com/upbound/provider-aws/v2/internal/native"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this ReplicationGroupRAW.
func (mg *ReplicationGroupRAW) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var mrsp reference.MultiNamespacedResolutionResponse
	var err error

	// GlobalReplicationGroupID resolves against native GlobalReplicationGroupRAW.
	// Uses registry lookup to avoid import cycle with v1beta1/native.
	{
		m, l, innerErr := apisresolver.GetManagedResource("elasticache.aws.upbound.io", "v1beta1", "GlobalReplicationGroupRAW", "GlobalReplicationGroupRAWList")
		if innerErr != nil {
			return errors.Wrap(innerErr, "failed to get the reference target managed resource and its list for reference resolution")
		}
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.GlobalReplicationGroupID),
			Extract:      native.ExtractAtProviderField("globalReplicationGroupId"),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.GlobalReplicationGroupIDRef,
			Selector:     mg.Spec.ForProvider.GlobalReplicationGroupIDSelector,
			To: reference.To{
				List:    l,
				Managed: m,
			},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.GlobalReplicationGroupID")
	}
	mg.Spec.ForProvider.GlobalReplicationGroupID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.GlobalReplicationGroupIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.KMSKeyID),
		Extract:      native.ExtractAtProviderField("arn"),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.KMSKeyIDRef,
		Selector:     mg.Spec.ForProvider.KMSKeyIDSelector,
		To: reference.To{
			List:    &v1beta1.KeyList{},
			Managed: &v1beta1.Key{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.KMSKeyID")
	}
	mg.Spec.ForProvider.KMSKeyID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.KMSKeyIDRef = rsp.ResolvedReference

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.SecurityGroupIds),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.ForProvider.SecurityGroupIDRefs,
		Selector:      mg.Spec.ForProvider.SecurityGroupIDSelector,
		To: reference.To{
			List:    &v1beta11.SecurityGroupList{},
			Managed: &v1beta11.SecurityGroup{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.SecurityGroupIds")
	}
	mg.Spec.ForProvider.SecurityGroupIds = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.SecurityGroupIDRefs = mrsp.ResolvedReferences

	// SubnetGroupName resolves against native SubnetGroupRAW.
	// Uses registry lookup to avoid import cycle with v1beta1/native.
	{
		m, l, innerErr := apisresolver.GetManagedResource("elasticache.aws.upbound.io", "v1beta1", "SubnetGroupRAW", "SubnetGroupRAWList")
		if innerErr != nil {
			return errors.Wrap(innerErr, "failed to get the reference target managed resource and its list for reference resolution")
		}
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SubnetGroupName),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.SubnetGroupNameRef,
			Selector:     mg.Spec.ForProvider.SubnetGroupNameSelector,
			To: reference.To{
				List:    l,
				Managed: m,
			},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.SubnetGroupName")
	}
	mg.Spec.ForProvider.SubnetGroupName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.SubnetGroupNameRef = rsp.ResolvedReference

	return nil
}
